
development:
  encoding: unicode
  adapter: postgresql
  username: postgres
  port: 5432
  host: localhost
  database: development_whitehorsefarm
  password: postgres

test:
  encoding: unicode
  adapter: postgresql
  username: postgres
  port: 5432
  host: localhost
  database: test_whitehorsefarm
  password: postgres

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
